### ISSUE TITLE
Running parallel tests crashes machine

### ISSUE THREAD

**Issue by seanlindo** [tatsuyafw/gulp-nightwatch#11]
Can you try passing in multiple environments into cliArgs and triggering a parallel test scenario? This consistently crashes my machine, but running directly through Nightwatch works fine. 

i.e. `cliArgs: ['--env chrome,firefox']`

**Comment by tatsuyafw** [comment]
Sorry for the late reply.

I'm afraid that a parallel test is not supported
I'll try to support this feature as soon as possible.

**Comment by tatsuyafw** [comment]
Hi @seanlindo .

I've fixed this bug, and released `v0.1.3`.
Please try it!
