### ISSUE TITLE
Support for nightwatch 0.6

### ISSUE THREAD

**Issue by luccamordente** [tatsuyafw/gulp-nightwatch#13]
Are you planning to support nightwatch 0.6? I'm trying to pass the --testcase but it's not supported on 0.5.
Thanks!

**Comment by tatsuyafw** [comment]
Hi @luccamordente .

I've updated nightwatch from 0.5 to 0.6 (#14).
Please try the latest version v0.1.2.

**Comment by luccamordente** [comment]
Working fine, thanks!
