### ISSUE TITLE
Support for parallel test execution as supported by nightwatch 0.7.5

### ISSUE THREAD

**Issue by rajeevzone** [tatsuyafw/gulp-nightwatch#18]
Nightwatch 0.7.5 supports parallel execution of tests. However, on defining test_worker on nightwatch.json file, the code errors out with error:  Error in plugin 'gulp-nightwatch'
 testAnalytics   undefined:1
--test
 ^
 testAnalytics   SyntaxError: Unexpected number
    at Object.parse (native)
    at Object.<anonymous> (/Users/...../Documents/workspace/nike-plus-web-friends/node_modules/nike-plus-web-test-automation/node_modules/gulp-nightwatch/lib/background.js:3:25)

nightwatch.json
"test_workers": {
          "enabled": true,
          "workers": "auto"
        }

**Comment by tatsuyafw** [comment]
Hi @rajeevzone .

I've confirmed that a parallel execution causes errors.

I'll try to fix this issue. Please wait for several days.

**Comment by tatsuyafw** [comment]
Hi @rajeevzone 

I think this issue is due to nigtwatch `v0.7.5`.
(See: https://github.com/nightwatchjs/nightwatch/issues/534)

When I updated the nightwatch to v0.7.6, and this issue no longer occurred.

Regards.

**Comment by rajeevzone** [comment]
Thanks @tatsuyafw.

This does fixes the issue.

Thanks,

**Comment by tatsuyafw** [comment]
Good :smile:
