### ISSUE TITLE
npm install does not download index.js

### ISSUE THREAD

**Issue by ankcrimson** [tatsuyafw/gulp-nightwatch#24]
npm install does not download index.js 
so we get the error as "gulp-nightwatch" module not found.
when downloaded manually, it runs fine.
Not sure how to fix this in npm

**Comment by peterbollen** [comment]
I'm having the same issue atm

**Comment by burkhardr** [comment]
Same here

**Comment by ankcrimson** [comment]
For the timebeing, we can download the file "https://raw.githubusercontent.com/tatsuyafw/gulp-nightwatch/master/index.js" manually and place it inside our node_modules/gulp-nightwatch directory, and the error will disappear :)

**Comment by tatsuyafw** [comment]
Hi @ankcrimson @peterbollen @burkhardr !

I've released `v0.2.4`, and confirmed the new version package includes `index.js`.
Could you use `v0.2.4`?

**Comment by ankcrimson** [comment]
Working good, thanks for the quick fix, closing this thread
