### ISSUE TITLE
nightwatch command line options

### ISSUE THREAD

**Issue by jameseisenhauer** [tatsuyafw/gulp-nightwatch#4]
Still working on understanding gulp plugins.  How do you run command line options for nightwatch?  Can you run multiple browsers at once.  It looks to me it just runs the default on the nightwatch.json config file.  Also for different browsers do you just create different nightwactch.json files?

what about other things like nightwatch tags?

thanks!

**Comment by tatsuyafw** [comment]
Hi @jameseisenhauer , thank you for your comment!

Now, `gulp-nightwatch` does not support command line options for nightwatch :disappointed: 

But I think, it's useful if nightwatch cli options are supported. I'll try to implement.

**Comment by jameseisenhauer** [comment]
that would be awesome!  thanks

**Comment by tatsuyafw** [comment]
@jameseisenhauer 

Sorry for late reply.
I've released `v0.1.0`, and it supports nightwatch command line options.
I hope you like it.

**Comment by jameseisenhauer** [comment]
Very cool.  Can't wait to update our projects and try it out!  I will also post to the nightwatchjs google group.  thanks again

**Comment by tatsuyafw** [comment]
I'm glad :smile:
