### ISSUE TITLE
Is this project still active? 

### ISSUE THREAD

**Issue by gared1212** [tatsuyafw/gulp-nightwatch#46]

**Comment by tatsuyafw** [comment]
@gared1212 

Yes. But I’ve not been able to devote time to this plugin lately. Pull requests welcome!

**Comment by rejas** [comment]
@tatsuyafw could you please publish a new version (with the gulp-util changes) to npm?

**Comment by tatsuyafw** [comment]
@rejas I've released as v0.3.3

**Comment by tatsuyafw** [comment]
I'm closing this issue.
